apiVersion: v1
kind: ConfigMap
metadata:
  name: reposerver
  labels:
    app.kubernetes.io/name: dbt
    app.kubernetes.io/component: reposerver
data:
  reposerver.json: |
    {
      "address": "0.0.0.0",
      "port": 9999,
      "serverRoot": "/var/dbt",
      "authGets": false,
      "authTypePut": "basic-htpasswd",
      "authOptsPut": {
        "idpFile": "/etc/dbt/htpasswd"
      }
    }
  htpasswd: |
    # Add users with: htpasswd -n username
    # Example: admin:$apr1$xyz...
