apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dbt

resources:
  - namespace.yaml
  - statefulset.yaml
  - service.yaml
  - configmap.yaml

# Override image tag in overlays:
#   kustomize edit set image ghcr.io/nikogura/dbt-reposerver:3.7.5
images:
  - name: ghcr.io/nikogura/dbt-reposerver
    newTag: latest
