apiVersion: v1
kind: Service
metadata:
  name: reposerver
  labels:
    app.kubernetes.io/name: dbt
    app.kubernetes.io/component: reposerver
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dbt
    app.kubernetes.io/component: reposerver
